export enum ERight {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  PERMISSION_MANAGEMENT = 'PERMISSION_MANAGEMENT',
  CAMP_MANAGEMENT = 'CAMP_MANAGEMENT',
  BENEF_MANAGEMENT = 'BENEF_MANAGEMENT',
  DONATION_MANAGEMENT = 'DONATION_MANAGEMENT',
  DONATION_APPROVE = 'DONATION_APPROVE',
  DONATION_REPORTING = 'DONATION_REPORTING',
  CAMP_REPORTING = 'CAMP_REPORTING',
  CAMP_IMPORT = 'CAMP_IMPORT',
  CAMP_REPORT_RESTRICTED = 'CAMP_REPORT_RESTRICTED',
}
