export enum ENotification{
  USER_UPDATED="USER_UPDATED",
  USER_DEACTIVATED="USER_DEACTIVATED",
  USER_DELETED="USER_DELETED",
  WELCOME_NEW_USER="WELCOME_NEW_USER",
  DONATION_APPROVED="DONATION_APPROVED"
}
